apiVersion: apps/v1
kind: Deployment
metadata:
  name: primevideo-deployment
  namespace: primevideo
spec:
  selector:
    matchLabels:
      app: primeapp
  template:
    metadata:
      labels:
        app: primeapp
    spec:
      containers:
      - name: primeapp
        image: rishindra2308/primevideoclone:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
