apiVersion: apps/v1
kind: Deployment
metadata:
  name: primevideo-clone-deployment
spec:
  selector:
    matchLabels:
      app: primevideo-clone
  template:
    metadata:
      labels:
        app: primevideo-clone
    spec:
      imagePullSecrets:
        - name: artifact-registry-secret
      containers:
        - name: primevideo-clone
          image: us-central1-docker.pkg.dev/devopslearning-463313/poc-repo/primevideo-clone-app:2
          ports:
            - containerPort: 3000