apiVersion: v1
kind: Service
metadata:
  name: primevideo-clone-service
  labels:
    app: primevideo-clone
spec:
  selector:
    app: primevideo-clone
  type: NodePort
  ports:
  - port: 3000  
    targetPort: 3000
    nodePort: 31000