name: DevSecOps CI
on:
    push:
        branches: [ main ]

jobs:
    Code-Quality:
        uses: ./.github/workflows/code-lint.yml
    Secret-Scanning:
        uses: ./.github/workflows/secret-scanning.yml
    Docker-Scans:
        uses: ./.github/workflows/docker-scans.yml